; Ver docs/decisions/0001-estructura-y-metodologia.md (por qué PlatformIO) y
; docs/decisions/0002-framework-arduino-vs-espidf.md (por qué framework = arduino).

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra
